name       : wingpanel-indicator-bluetooth
version    : 2.1.3
release    : 2
source     :
    - https://github.com/elementary/wingpanel-indicator-bluetooth/archive/2.1.3.tar.gz : 5d82ac36dc424790e1dbc453b5ce02134dead5431877f798dcd6a786d6e60e55
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Wingpanel bluetooth indicator
description: |
    Wingpanel inicator for bluetooth settings and informations.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(granite)
    - pkgconfig(libnotify)
    - glib2-devel
    - meson
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
