name       : code
version    : 1.31.1
release    : 1
source     :
    - https://az764295.vo.msecnd.net/stable/1b8e8302e405050205e69b59abb3559592bb9e60/code_1.31.1-1549938243_amd64.deb : fb47deec394997fb6b9f06ed6d0c8417b163f82794a8dd90eb1aa8776b4009f9
license    : GPLv3
summary    : Visual Studio Code.
description: |
    Visual Studio Code.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
