name       : pantheon-code
version    : 3.1.1
release    : 1
source     :
    - https://github.com/elementary/code/archive/3.1.1.tar.gz : 09df216f93967ba499a7de1ea6f5af0601cc61bc77462ff3ea809094d8c3aaa0
license    : GPL-3.0
component  : programming.tools
summary    : Pantheon code editor app 
description: |
    Code editor designed for elementary OS.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libgit2-glib-1.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
