name       : switchboard-plug-about
version    : 2.5.2
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-about/archive/2.5.2.tar.gz : 2f5ed765956da00183b6a884fff8013b383602e238eecd2be3253767d01a2bfb
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard about plug
description: |
    About plug for Switchboard which displays information about the system.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
