name       : appstream
version    : 0.12.6
release    : 2
source     :
    - https://www.freedesktop.org/software/appstream/releases/AppStream-0.12.6.tar.xz : ab20067036207aa0708608f87d6e2043ec46fad0b55b411eb1f242b8b9ab0d14
license    : GPL-2.0
summary    : Software component metadata management.
networking : true
description: |
    Software component metadata management.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    - docbook-xml
    - glib2-devel
    - gperf
    - gtk-doc
    - meson
    - stemmer-devel
    - vala
setup      : |
    %meson_configure -Ddocs=false -Dvapi=true
build      : |
    %meson_build
install    : |
    %meson_install
