name       : appstream
version    : 0.12.5
release    : 1
source     :
    - git|https://git.launchpad.net/ubuntu/+source/appstream : applied/0.12.5-1
license    : GPLv3
component  : desktop.pantheon
summary    : Software component metadata management.
networking : true
description: |
    Software component metadata management.
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    - docbook-xml
    - meson
    - gperf
    - vala
    - gtk-doc
    - stemmer-devel
setup      : |
    %meson_configure -Ddocs=false -Dvapi=true
build      : |
    %meson_build
install    : |
    %meson_install
