name       : appstream
version    : 0.12.2
release    : 1
source     :
    - http://archive.ubuntu.com/ubuntu/pool/main/a/appstream/appstream_0.12.0.orig.tar.xz : 28b5aeb59161db003b4eade23e0f539f0def34e9428f268f154ae6226c924ed7
license    : GPLv3
component  : desktop.pantheon
summary    : Software component metadata management.
networking : true
description: |
    Software component metadata management.
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    - docbook-xml
    - meson
    - gperf
    - vala
    - gtk-doc
    - stemmer-devel
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %meson_build
install    : |
    %meson_install
