name       : switchboard-plug-pantheon-shell
version    : 2.8.1
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-pantheon-shell/archive/2.8.1.tar.gz : 79d9a1ea220e1564c739fc2e07d4481d35f8a46f9c23c505c46b2cd754434ee2
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard desktop plug
description: |
    Switchboard plug for controlling Pantheon Shell.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(plank)
    - pkgconfig(switchboard-2.0)
    - meson
    - vala
setup      : |
    %meson_configure -Dlibunity='false'
build      : |
    %meson_build
install    : |
    %meson_install
