name       : switchboard-plug-pantheon-shell
version    : 2.8.0
release    : 1
source     :
    - https://github.com/elementary/switchboard-plug-pantheon-shell/archive/2.8.0.tar.gz : 46432b5e0b87f952e227fc145357f2816ddbbc6eda5382e336fc6d79cc5c5cac
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Desktop Plug.
description: |
    Switchboard Desktop Plug.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - libgnome-desktop-devel
    - gexiv2-devel
    - plank-devel
    - switchboard-devel
    - meson
    - vala
setup      : |
    %meson_configure -Dlibunity='false'
build      : |
    %meson_build
install    : |
    %meson_install
