name       : elementary-dpms-helper
version    : 1.0
release    : 1
source     :
    - git|https://github.com/elementary/dpms-helper.git : 1.0
license    : GPLv3
component  : desktop.pantheon
summary    : Sets DPMS settings found in org.pantheon.dpms.
description: |
    Sets DPMS settings found in org.pantheon.dpms.
builddeps  :
    - desktop-file-utils
    - meson
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
