name       : wingpanel-indicator-network
version    : 2.2.2
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-network.git : 2.2.2
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Network Indicator.
description: |
    Wingpanel Network Indicator.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - glib2-devel
    - gobject-introspection-devel
    - network-manager-devel
    - network-manager-applet-devel
    - wingpanel-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
