name       : megasync
version    : 4.2.3.1.1
release    : 14
source     :
    - https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megasync-Debian_10.0_amd64.deb : e7fef09c71eaa99922c35777cc30efe4114d96a292309805f2b4050518eafa08
license    : Mega Limited Code Review License
component  : network.clients
summary    : Mega account files syncer
description: |
    Easy automated syncing between your computers and your Mega Cloud Drive.
builddeps  :
    - pkgconfig(libglvnd)
    - binutils
    - tar
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*