name       : stemmer
version    : 1
release    : 2
source     :
    - https://github.com/snowballstem/snowball/archive/d29510ae32702a81cdc29177a133e894df854550.tar.gz : 0ddced2e7dd6367dcda2417460e1a64ac22723300e671ecf465b1da46d4875b7
license    : BSD-3-Clause
summary    : Snowball stemming algorithms, development kit
description: |
    Snowball is a small string processing language designed for creating stemming algorithms for use in Information Retrieval.
    The Snowball compiler translates a Snowball script into another language - currently ISO C, C#, Go, Java, Javascript, Object Pascal, Python and Rust are supported.
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    mkdir -p $installdir/usr/include
    mkdir -p $installdir/usr/lib/include
    install -Dm644 {.,$installdir/usr}/include/libstemmer.h
    install -D {.,$installdir/usr/lib}/libstemmer.so.0.0.0
    ln -s libstemmer.so.0.0.0 "$installdir/usr/lib/libstemmer.so.0"
    ln -s libstemmer.so.0 "$installdir/usr/lib/libstemmer.so"
    install -Dm644 COPYING "$installdir/usr/share/licenses/libstemmer/LICENSE"
