name       : pantheon-default-settings
version    : 5.1.0
release    : 4
source     :
    - https://github.com/elementary/default-settings/archive/5.1.0.tar.gz : 01f22de085a73eb546eb760d3b3b960da0f1dbe7b78370f1f13d6bcdea707163
license    : GPL-1.0
component  : desktop.pantheon
summary    : Pantheon default settings
description: |
    Default settings for Pantheon desktop.
rundeps:
    - font-clear-sans-ttf
    - font-roboto-ttf
install    : |
    install -Dm 644 overrides/default-settings.gschema.override $installdir/usr/share/glib-2.0/schemas/25_pantheon-default-settings.gschema.override
    install -Dm 644 settings.ini -t $installdir/etc/gtk-3.0/
    install -dm 755 $installdir/etc/skel/.config
    cp -dr --no-preserve='ownership' plank $installdir/etc/skel/.config/
    cp -dr --no-preserve='ownership' profile.d $installdir/etc/
