name       : pantheon-default-settings
version    : 5.0
release    : 1
source     :
    - git|https://github.com/elementary/default-settings.git : 5.0
license    : GPLv3
component  : desktop.pantheon
summary    : Default settings for Pantheon.
description: |
    Default settings for Pantheon.
install    : |
    install -Dm 644 overrides/default-settings.gschema.override $installdir/usr/share/glib-2.0/schemas/25_pantheon-default-settings.gschema.override
    install -Dm 644 settings.ini -t $installdir/etc/gtk-3.0/
    install -dm 755 $installdir/etc/skel/.config
    cp -dr --no-preserve='ownership' plank $installdir/etc/skel/.config/
    cp -dr --no-preserve='ownership' profile.d $installdir/etc/
