name       : pantheon-camera
version    : 1.0.4
release    : 1
source     :
    - https://github.com/elementary/camera/archive/1.0.4.tar.gz : 29a391df0e50cdce950d1240a79e6c72cd56b86b77d8096e36e54195bf110196
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon camera app
description: |
    Desktop camera app designed for elementary OS.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - appstream
    - desktop-file-utils
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
