name       : elementary-sound-theme
version    : 1.0
release    : 1
source     :
    - git|https://github.com/elementary/sound-theme.git : 1.0
license    : GPLv3
component  : desktop.pantheon
summary    : A bespoke sound for your theme.
description: |
    A bespoke sound for your theme.
builddeps  :
    - meson
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
