name       : switchboard-plug-bluetooth
version    : 2.2.2
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-bluetooth/archive/2.2.2.tar.gz : 6aef5482246a1d413f7152623b8af10139436bbbe9ebee94264d07a18ac11af6
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard bluetooth plug
description: |
    Bluetooth plug for Switchboard which configures bluetooth devices.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
