name       : xfwm4
version    : 4.14.0
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/xfwm4/4.14/xfwm4-4.14.0.tar.bz2 : b4182bf8dc63d092f120a51fcae0eb54b9bd4aa4f8486f47e5a65a108322b615
license    : GPL-2.0
component  : desktop. xfce
summary    : Xfce's window manager
description: |
    Window manager for Xfce.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfce4util-1.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xrender)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install