name       : spotitube
version    : 25
release    : 3
source     :
    - https://github.com/streambinder/spotitube/releases/download/v25/spotitube-v25.deb : bcca690b7cd337411058e65b29a01e716f17f0306dc08aa16a8d412224fde58e
license    : GPL-3.0
component  : network.clients
summary    : Shell application to incrementally download from Spotify into local folder
networking : true
description: |
    Programmatically authenticate to your Spotify account and synchronize your music, keeping playlists files, metadata informations, album artworks, songs lyrics and maximizing mp3 files quality.
setup      : |
    mkdir -p $installdir
install    : |
    tar -xf data.tar.xz --strip 1 -C $installdir
