name       : spotitube
version    : 24
release    : 1
source     :
    - git|https://github.com/streambinder/spotitube.git : v24
license    : GPLv3
component  : network.clients
summary    : Shell go-lang application to incrementally download from Spotify into local folder.
networking : true
description: |
    Programmatically authenticate to your Spotify account and synchronize your music, keeping playlists files, metadata informations, album artworks, songs lyrics and maximizing mp3 files quality.
builddeps  :
    - golang
    - git
setup      : |
    cd $workdir
    %make deps
build      : |
    %make
install    : |
    install -Dm 755 $workdir/out/spotitube $installdir/usr/sbin/spotitube
