name       : xfce4-settings
version    : 4.14.1
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/xfce4-settings/4.14/xfce4-settings-4.14.1.tar.bz2 : e873e9f6b8e801fd9304ee100c4c76ed9987446c38429d02477c086431c0bf7a
license    : GPL-2.0
component  : desktop.xfce
summary    : Xfce Settings
description: |
    Xfce's configuration system.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install