name       : switchboard-plug-printers
version    : 2.1.6
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-printers/archive/2.1.6.tar.gz : fe2c748e3737c3304ea8613d43d5ba8596f95499a65b8d13f93c4f702901f442
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard printers plug
description: |
    Printers plug for Switchboard which configures all available printers.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - cups-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
