name       : wingpanel-indicator-power
version    : 2.1.3
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-power.git : 2.1.3
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Power Indicator.
description: |
    Wingpanel Power Indicator.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - bamf-devel
    - libgtop-devel
    - libgudev-devel
    - wingpanel-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
