name       : wingpanel-indicator-keyboard
version    : 2.1.1
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-keyboard.git : 2.1.1
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Keyboard Indicator.
description: |
    Wingpanel Keyboard Indicator.
builddeps  :
    - pkgconfig(granite)
    - glib2-devel
    - wingpanel-devel
    - gobject-introspection-devel
    - libxml2-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
