name       : wingpanel-indicator-keyboard
version    : 2.1.2
release    : 2
source     :
    - https://github.com/elementary/wingpanel-indicator-keyboard/archive/2.1.2.tar.gz : 25b214825a5402c1918ab39c93d64b2d38379683c7f25fd4d3f22e8930e0bc94
license    : GPL-3.0
component  : desktop.pantheon
summary    : Wingpanel keyboard indicator
description: |
    Wingpanel inicator for keyboard settings and informations.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(granite)
    - pkgconfig(libxml-2.0)
    - glib2-devel
    - meson
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
