name       : libsignon-glib
version    : 2.1
release    : 2
source     :
    - https://gitlab.com/accounts-sso/libsignon-glib/-/archive/VERSION_2.1/libsignon-glib-VERSION_2.1.tar.gz : 574c865b45b422c4a56fbfa13384246d37a7b532f1991b5e851b5dbf3e817587
    - https://gitlab.com/accounts-sso/signon-dbus-specification/-/archive/master/signon-dbus-specification-master.tar.gz : bf4b76a5e98167359c5505da700020d2c27608307e131e993721cb3c4257ddf8
license    : LGPL-2.1
summary    : GLib library to interface with the Signon Daemon
description: |
    This project is a library for managing single signon credentials which can be used from GLib applications.
    It is effectively a GLib binding for the D-Bus API provided by signond
builddeps  :
    - pkgconfig(check)
    - pkgconfig(gobject-introspection-1.0)
    - glib2-devel
    - gtk-doc-devel
    - meson
    - vala
setup      : |
    tar -xf $sources/signon-dbus-specification-master.tar.gz --strip 1 -C libsignon-glib/interfaces/
    %meson_configure -Dpython=false
build      : |
    %meson_build
install    : |
    %meson_install
