name       : libstatgrab
version    : 0.91
release    : 1
source     :
    - https://github.com/libstatgrab/libstatgrab/releases/download/LIBSTATGRAB_0_91/libstatgrab-0.91.tar.gz : 03e9328e4857c2c9dcc1b0347724ae4cd741a72ee11acc991784e8ef45b7f1ab
license    : GPL-2.0
component  : desktop.library
summary    : A cross platform library for accessing system statistics
description: |
    libstatgrab is a library that provides cross platform access to statistics about the system on which it's run.
    It's written in C and presents a selection of useful interfaces which can be used to access key system statistics.
    The current list of statistics includes CPU usage, memory utilisation, disk usage, process counts, network traffic, disk I/O, and more.
    The current list of supported and tested platforms includes FreeBSD, Linux, NetBSD, OpenBSD, Solaris, DragonFly BSD, HP-UX and AIX.
    We are always happy to accept patches to extend support to other operating systems.
    The package also includes a couple of useful tools.
    The first, saidar, provides a curses-based interface to viewing the current state of the system.
    The second, statgrab, gives a sysctl-style interface to the statistics gathered by libstatgrab.
    This extends the use of libstatgrab to people writing scripts or anything else that can't easily make C function calls.
    Included with statgrab is a script to generate an MRTG configuration file to use statgrab.
    The library part of libstatgrab is licensed under the GNU LGPL, but the tools and examples are licensed under the GNU GPL.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
