name       : pantheon-applications-menu
version    : 2.4.2
release    : 2
source     :
    - git|https://github.com/elementary/applications-menu.git : 2.4.2
license    : GPLv3
component  : desktop.pantheon
summary    : Lightweight and stylish Pantheon app launcher.
description: |
    Lightweight and stylish Pantheon app launcher.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(libvala-0.40)
    - pkgconfig(libmutter-2)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(wingpanel-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(zeitgeist-2.0)
    - pkgconfig(switchboard-2.0)
    - pkgconfig(appstream)
    - pkgconfig(plank)
    - plank
    - meson
    - vala
    - gala-devel
setup      : |
    patch -Np1 --ignore-whitespace -i ../../../../../work/files/plank.patch
    %meson_configure -Dwith-unity='false'
build      : |
    %meson_build
install    : |
    %meson_install
    mkdir -p $installdir/usr/share/glib-2.0/schemas/
    mkdir -p $installdir/usr/share/xdg/menus
    install io.elementary.desktop.wingpanel.applications-menu.gschema.xml $installdir/usr/share/glib-2.0/schemas/
    install data/pantheon-applications.menu $installdir/usr/share/xdg/menus
