name       : switchboard-plug-keyboard
version    : 2.3.5
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-keyboard/archive/2.3.5.tar.gz : 76f02f8de6c65a45779c6774c2f82c096e0b44fb6e899edcd0c45b713d76e1fa
license    : GPL-2.0
component  : desktop.pantheon
summary    : Switchboard keyboard plug
description: |
    Switchboard plug for keyboard settings which can be used to change several keyboard settings, for example the delay and speed of the key repetition, or the cursor blinking speed.
    You can change your keyboard layout, and use multiple layouts at the same time.
    Keyboard shortcuts are also part of this plug.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbd)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
