name       : melody
version    : 2.2.0
release    : 3
source     :
    - https://github.com/artemanufrij/playmymusic/archive/2.2.0.tar.gz : 810a038980f579a11314cb88c9c048838b88d9f6fc9132ee146323170027d866
license    : GPL-3.0
component  : multimedia.audio
summary    : A music player for listening to local music files, online radios and audio CDs
description: |
    A very fast music player designed extra for large local libraries which also supports online radios and downloading album covers.
    It features showing all albums from your library, grouping tracks by artists, managing your playlists, listening to online radio, managing MTP devices, audio CD and ID3-tag support.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - meson
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
