name       : melody
version    : 2.2.0
release    : 2
source     :
    - git|https://github.com/artemanufrij/playmymusic.git : 2.2.0
license    : GPLv2
component  : multimedia.audio
summary    : A music player for listening to local music files, online radios, and Audio CDs.
description: |
    A music player for listening to local music files, online radios, and Audio CDs.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - meson
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
