name       : wingpanel-indicator-nightlight
version    : 2.0.1
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-nightlight.git : 2.0.1
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Nightlight Indicator.
description: |
    Wingpanel Nightlight Indicator.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - glib2-devel
    - wingpanel-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
