name       : wingpanel-indicator-a11y
version    : 1
release    : 1
source     :
    - https://github.com/elementary/wingpanel-indicator-a11y/archive/master.zip : 3eec6a17f699c92ade95025bfbebb410bbc2edb0e61a7254521ec71acfe766a5
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Universal Access Indicator.
description: |
    Wingpanel Universal Access Indicator.
builddeps  :
    - pkgconfig(granite)
    - wingpanel-devel
    - meson
    - vala
setup      : |
    patch -Np1 --ignore-whitespace -i ../../../../../work/files/po.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
