name       : wingpanel-indicator-a11y
version    : 1
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-a11y.git : 6507008552dca302c1cac85dfdeb05ba64361ba6
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Universal Access Indicator.
description: |
    Wingpanel Universal Access Indicator.
builddeps  :
    - pkgconfig(granite)
    - wingpanel-devel
    - meson
    - vala
setup      : |
    patch -Np1 --ignore-whitespace -i ../../../../../work/files/po.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
