name       : pantheon-appstream-data
version    : 5.0
release    : 1
source     :
    - https://blueprints.launchpad.net/~elementary-os/+archive/ubuntu/stable/+build/15165197/+files/appstream-data-pantheon_5.0-0+r37~ubuntu18.04.1_all.deb : fbec3f1784b1f3f606bc15310db78aeacc8922c5508faa64ea34302c85df4a79
    - https://blueprints.launchpad.net/~elementary-os/+archive/ubuntu/stable/+build/15165197/+files/appstream-data-pantheon-icons_5.0-0+r37~ubuntu18.04.1_all.deb : 7670abfa22b4ff437cb25b580fab7fc4d47b5c98f0fd9a0c1fb29849b5b73a28
    - https://blueprints.launchpad.net/~elementary-os/+archive/ubuntu/stable/+build/15165197/+files/appstream-data-pantheon-icons-hidpi_5.0-0+r37~ubuntu18.04.1_all.deb : 94d84cc3cd9aa8a62a784a659393b9cefbf2bab2b3a1f003abff19694eedad63
license    : Unknown
component  : desktop.pantheon
summary    : AppStream data for Pantheon
networking : true
description: |
    AppStream data for Pantheon.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
    ls -l $sources
    cd $sources
    for pkg in *.deb; do
        ar x $pkg
        cd $installdir
        tar xvf $sources/data.tar.*
        cd -
    done
install    : |
    cd $installdir
