name       : switchboard-plug-notifications
version    : 2.1.5
release    : 1
source     :
    - https://github.com/elementary/switchboard-plug-notifications/archive/2.1.5.tar.gz : afbce598515dfae4b1f57db75f9fbca2c2b17dc9ba3ba3c2012c521488b0bbc9
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Notifications Plug.
description: |
    Switchboard Notifications Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - switchboard-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
