name       : libgsignon-glib
version    : 2.4.1
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/libgsignon-glib.git : a10da2694106fe6de4587278e09dc85e72b33ae2
license    : GPLv3
summary    : gSSO client library.
description: |
    gSSO client library.
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - gtk-doc-devel
    - meson
    - vala
setup      : |
    %autogen --prefix='/usr' --enable-dbus-type='session' --enable-introspection='yes'
build      : |
    %make
install    : |
    %make_install
    libtool --finish /usr/lib64
