name       : wingpanel-indicator-notifications
version    : 2.1.2
release    : 1
source     :
    - https://github.com/elementary/wingpanel-indicator-notifications/archive/2.1.2.tar.gz : 0824c6c75b4faa7ca21dd47c4bf8f4380474734f78b410ef9b9d2ff4de8c7f26
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Notifications Indicator.
description: |
    Wingpanel Notifications Indicator.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - gdk-pixbuf-devel
    - libwnck-devel
    - glib2-devel
    - wingpanel-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
