name       : wingpanel-indicator-notifications
version    : 2.1.2
release    : 2
source     :
    - https://github.com/elementary/wingpanel-indicator-notifications/archive/2.1.2.tar.gz : 0824c6c75b4faa7ca21dd47c4bf8f4380474734f78b410ef9b9d2ff4de8c7f26
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Wingpanel notifications indicator
description: |
    Wingpanel inicator for notifications settings and informations.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - glib2-devel
    - meson
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
