name       : pantheon-onboarding
version    : 20190624
release    : 1
source     :
    - https://github.com/elementary/onboarding/archive/master.tar.gz : d228763abfdaedf84085c0f865347d29e5d96ee142214eee987facfed8e30880
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon onboarding app
description: |
    Onboarding app designed for elementary OS.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
