name       : pantheon-greeter
version    : 3.3.1
release    : 1
source     :
    - git|https://github.com/elementary/greeter.git : 3.3.1
license    : GPLv3
component  : desktop.pantheon
summary    : LightDM Greeter for Pantheon.
description: |
    LightDM Greeter for Pantheon.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libvala-0.40)
    - pkgconfig(libmutter-2)
    - pkgconfig(wingpanel-2.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - lightdm-devel
    - gnome-settings-daemon-devel
    - lightdm-devel
    - libx11-devel
    - gdk-pixbuf-devel
    - desktop-file-utils
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
