name       : pantheon-greeter
version    : 3.3.1
release    : 4
source     :
    - https://github.com/elementary/greeter/archive/3.3.1.tar.gz : f7068bf8120bd535aacb56b40c235fad09845347a00fb0e4f07240674a5ff534
license    : GPL-3.0
component  : desktop.pantheon
summary    : LightDM Greeter for Pantheon
description: |
    Pantheon Greeter is a pantheon-styled Login Screen for LightDM.
    It is elementary OS default login screen.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(libmutter-2)
    - pkgconfig(libvala-0.44)
    - pkgconfig(wingpanel-2.0)
    - pkgconfig(x11)
    - desktop-file-utils
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
