name       : nemo
version    : 4.2.2
release    : 1
source     :
    - https://github.com/linuxmint/nemo/archive/4.2.2.tar.gz : b9241fc3e4cc5fe094d478c494aaa117f0f2a6e077b576b00f2bea2cb26b24ab
license    : GPL-2.0
component  : desktop.cinnamon
summary    : File browser for Cinnamon
description: |
    Nemo is the file manager for the Cinnamon desktop environment.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(exempi-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libexif)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(libnotify)
    - pkgconfig(tracker-control-2.0)
    - pkgconfig(xapp)
    - pkgconfig(xkbfile)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install