name       : switchboard-plug-online-accounts
version    : 0.3.0.1
release    : 1
source     :
    - https://launchpad.net/switchboard-plug-onlineaccounts/loki/0.3.0.1/+download/switchboard-plug-onlineaccounts-0.3.0.1.tar.xz : ac7fdaebdab65403fd7e2776d381a0e205bc131a5acf6d29420b2dbaae3680a9
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Online Accounts Plug.
description: |
    Switchboard Online Accounts Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - libwebkit-gtk-devel
    - libaccounts-glib-devel
    - librest-devel
    - switchboard-devel
    - gsignond-devel
    - libgsignon-glib-devel
    - meson
    - vala
setup      : |
    %cmake -DCMAKE_BUILD_TYPE='Release' -DCMAKE_INSTALL_PREFIX='/usr' -DCMAKE_INSTALL_LIBDIR='/usr/lib'
build      : |
    %make
install    : |
    %make_install
