name       : switchboard-plug-online-accounts
version    : 2.0.1
release    : 1
source     :
    - git|https://github.com/elementary/switchboard-plug-onlineaccounts.git : 2.0.1
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Online Accounts Plug.
description: |
    Switchboard Online Accounts Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgsignon-glib)
    - libwebkit-gtk-devel
    - libaccounts-glib-devel
    - librest-devel
    - switchboard-devel
    - gsignond-devel
    - meson
    - vala
setup      : |
    patch -Np1 --ignore-whitespace -i ../../../../../work/files/libsignon-glib.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
