name       : elementary-stylesheet
version    : 5.2.1
release    : 1
source     :
    - https://github.com/elementary/stylesheet/archive/5.2.1.tar.gz : b6104a5380a77ea1634706afb749b6ea482e98af970d134fe00a7b0fcb841934
license    : GPLv3
component  : desktop.pantheon
summary    : The Gtk+ Stylesheet for elementary OS.
description: |
    The Gtk+ Stylesheet for elementary OS.
builddeps  :
    - meson
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
