name       : elementary-stylesheet
version    : 5.2.1
release    : 1
source     :
    - git|https://github.com/elementary/stylesheet.git : 5.2.1
license    : GPLv3
component  : desktop.pantheon
summary    : The Gtk+ Stylesheet for elementary OS.
description: |
    The Gtk+ Stylesheet for elementary OS.
builddeps  :
    - meson
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
