name       : wingpanel-indicator-bluetooth
version    : 2.1.2
release    : 1
source     :
    - https://github.com/elementary/wingpanel-indicator-bluetooth/archive/2.1.2.tar.gz : 93ba8995eeea16a33ff0fe38efda1f7d892a4306623e9f48891c3842b87edf98
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Bluetooth Indicator.
description: |
    Wingpanel Bluetooth Indicator.
builddeps  :
    - pkgconfig(granite)
    - wingpanel-devel
    - gobject-introspection-devel
    - glib2-devel
    - libnotify-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
