name       : wingpanel-indicator-sound
version    : 2.1.3
release    : 2
source     :
    - https://github.com/elementary/wingpanel-indicator-sound/archive/2.1.3.tar.gz : e69cba0553d98665ad9a44576ef5228cdc2f47f6c816071393dd7454b6272278
license    : GPL-3.0
component  : desktop.pantheon
summary    : Wingpanel sound indicator
description: |
    Wingpanel inicator for sound settings and informations.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - glib2-devel
    - meson
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
