name       : switchboard-plug-display
version    : 2.1.8
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-display/archive/2.1.8.tar.gz : 508c952532dae21e2c8927cb4d84f1e3e6db4e97c796ed3bed5c523258b2fbd2
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard display plug
description: |
    Switchboard plug for display settings which can be used to change display settings like orientation and resolution.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
