name       : contractor
version    : 0.3.4
release    : 1
source     :
    - git|https://github.com/elementary/contractor.git : 0.3.4
license    : GPLv3
component  : desktop.pantheon
summary    : A desktop-wide extension service used by elementary OS.
description: |
    A desktop-wide extension service used by elementary OS.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
