name       : pantheon-music
version    : 5.0.4
release    : 1
source     :
    - https://github.com/elementary/music/archive/5.0.4.tar.gz : 375b9e4d7c6c842eb0d738e5073cf28198328768df2f3a2fa9895bc194a41d94
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon music app
description: |
    Desktop music app designed for elementary OS.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsignon-glib)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(taglib)
    - pkgconfig(zeitgeist-2.0)
    - glib2-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
