name       : wingpanel
version    : 2.2.5
release    : 4
source     :
    - https://github.com/elementary/wingpanel/archive/2.2.5.tar.gz : c409c8cc3d935a9c31991eb572d59f9a810ed428aeae2be53491e47e149102c6
license    : GPL-3.0
component  : desktop.pantheon
summary    : Stylish top panel that holds indicators and spawns the application launcher
description: |
    A super sexy space-saving top panel and replacement for the traditional GNOME Panel, designed to be a lightweight container for system/application indicators and notification icons.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmutter-2)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libvala-0.44)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gala-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
