name       : pantheon-keyboard
version    : 20190624
release    : 1
source     :
    - https://github.com/elementary/keyboard/archive/master.tar.gz : 047ab60cf37fff13274579b64a8d097e357540f54fb7302875fe3f995606c060
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon on-screen keyboard app
description: |
    Desktop on-screen jeyboard app designed for elementary OS.
builddeps  :
    - pkgconfig(caribou-1.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
