name       : gsignond-plugin-sasl
version    : 1
release    : 1
source     :
    - https://gitlab.com/accounts-sso/gsignond-plugin-sasl/-/archive/master/gsignond-plugin-sasl-master.tar.gz : 0e6c0216035118204a6ff2b91f4530382c6fd689235f215fe24026370bcb6802
license    : GPLv3
summary    : SASL plugin for gSSO.
description: |
    SASL plugin for gSSO.
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - glibc-devel
    - gsignond-devel
    - gsasl-devel
    - check-devel
    - gtk-doc-devel
    - meson
setup      : |
    %meson_configure -Ddocumentation='false'
build      : |
    %meson_build
install    : |
    %meson_install
