name       : gsignond-plugin-sasl
version    : 1
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/gsignond-plugin-sasl.git : b304c70b7dad9368b23b1205122d10de684c896a
license    : GPLv3
summary    : SASL plugin for gSSO.
description: |
    SASL plugin for gSSO.
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - glibc-devel
    - gsignond-devel
    - gsasl-devel
    - check-devel
    - gtk-doc-devel
    - meson
setup      : |
    %meson_configure -Ddocumentation='false'
build      : |
    %meson_build
install    : |
    %meson_install
