name       : megasync-nautilus
version    : 3.6.6
release    : 6
source     :
    - https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/nautilus-megasync-Debian_10.0_amd64.deb : ad425ca18c2da15a42517d26920e775d0843301c1a20c17baa9fac6eee72d214
license    : Mega Limited Code Review License
summary    : Nautilus extension for megasync
description: |
    Extension for megasync to upload your files to your Mega account from nautilus.
builddeps  :
    - binutils
    - tar
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*