name       : switchboard-plug-mouse-touchpad
version    : 2.2.0
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-mouse-touchpad/archive/2.2.0.tar.gz : 22052f2289c6c47dacedc5c5bc3bad8f2a559f39a05f65422b25ebac847b24cb
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard mouse and touchpad plug
description: |
    Plug for Switchboard which configures mouse and touchpad.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
