name       : switchboard-plug-mouse-touchpad
version    : 2.1.4
release    : 1
source     :
    - git|https://github.com/elementary/switchboard-plug-mouse-touchpad.git : 2.1.4
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Mouse & Touchpad Plug.
description: |
    Switchboard Mouse & Touchpad Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - glib2-devel
    - glibc-devel
    - switchboard-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
