name       : switchboard-plug-power
version    : 2.3.4
release    : 1
source     :
    - https://github.com/elementary/switchboard-plug-power/archive/2.3.4.tar.gz : 254834e0f2be4b2b8542a61afa5bf677bab782f0e887264c18ee53cc694a9d73
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Power Plug.
description: |
    Switchboard Power Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - glibc-devel
    - glib2-devel
    - polkit-devel
    - switchboard-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
