name       : switchboard-plug-locale
version    : 2.4.1
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-locale/archive/2.4.1.tar.gz : 3455119cc82f1fb644353766afde3faa41f42beb43f65721dce87614b6482d0b
license    : LGPL-3.0
component  : desktop.pantheon
summary    : Switchboard locale plug
description: |
    Region and language plug for Switchboard which manages your region and language settings.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - libgnome-desktop-docs
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
