name       : wingpanel-indicator-session
version    : 2.2.2
release    : 1
source     :
    - git|https://github.com/elementary/wingpanel-indicator-session.git : 2.2.2
license    : GPLv3
component  : desktop.pantheon
summary    : Wingpanel Session Indicator.
description: |
    Wingpanel Session Indicator.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - accountsservice-devel
    - glib2-devel
    - wingpanel-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
