name       : wingpanel-indicator-session
version    : 2.2.3
release    : 2
source     :
    - https://github.com/elementary/wingpanel-indicator-session/archive/2.2.3.tar.gz : 45f7582c9335257808d1b41af928c40692e7b5a448daf59d38049914993ee2c2
license    : GPL-2.0
component  : desktop.pantheon
summary    : Wingpanel session indicator
description: |
    Wingpanel inicator for session settings and informations.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - glib2-devel
    - meson
    - vala
    - wingpanel-devel
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
