name       : gsasl
version    : 1.8.0
release    : 1
source     :
    - ftp://ftp.gnu.org/gnu/gsasl/gsasl-1.8.0.tar.gz : 310262d1ded082d1ceefc52d6dad265c1decae8d84e12b5947d9b1dd193191e5
license    : GPL
summary    : Simple Authentication and Security Layer framework and a few common SASL mechanisms.
description: |
    Simple Authentication and Security Layer framework and a few common SASL mechanisms.
builddeps  :
    - libgnutls-devel
    - libidn-devel
    - kerberos-devel
    - libgcrypt-devel
setup      : |
    %configure --prefix=/usr --with-gssapi-impl=mit
build      : |
    %make
install    : |
    %make_install
