name       : gsignond-plugin-oauth
version    : 1
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/gsignond-plugin-oa.git : d471cebfd7c50567b1244277a9559f18f8d58691
license    : LGPL2.1
summary    : OAuth plugin for gSSO.
description: |
    OAuth plugin for gSSO.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - glib2-devel
    - glibc-devel
    - gsignond-devel
    - libgnutls-devel
    - check-devel
    - gtk-doc-devel
    - meson
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
