name       : switchboard-plug-power
version    : 2.3.5
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-power/archive/2.3.5.tar.gz : 56aee47f37d3205d1a6a49347743cab80d0f5a92b43ab592d43f86a971564e53
license    : GPL-2.0
component  : desktop.pantheon
summary    : Switchboard power plug
description: |
    Power plug for Switchboard which configures system power consumption.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - meson
    - polkit-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
