name       : megasync-dolphin
version    : 4.1.1.3.1
release    : 1
source     :
    - https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/dolphin-megasync-Debian_10.0_amd64.deb : 4cf106bc090f4cfa5f8a0eb4bf9bf13d99a121dd455d00c3622a03c1aef9b5c5
license    : Mega Limited Code Review License
summary    : Dolphin extension for megasync
description: |
    Extension for megasync to upload your files to your Mega account from dolphin.
builddeps  :
    - binutils
    - tar   
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*