name       : switchboard-plug-display
version    : 2.1.6
release    : 1
source     :
    - https://github.com/elementary/switchboard-plug-display/archive/2.1.6.tar.gz : 7189295d0467002f448ea37bf824918118f4b9a2d208a44badb7f4d449c8bb7b
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Displays Plug.
description: |
    Switchboard Displays Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - switchboard-devel
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
