name       : switchboard
version    : 2.3.5
release    : 1
source     :
    - git|https://github.com/elementary/switchboard.git : 2.3.5
license    : GPLv3
component  : desktop.pantheon
summary    : Extensible System Settings app designed for elementary OS.
description: |
    Extensible System Settings app designed for elementary OS.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - meson
    - vala
setup      : |
    %meson_configure -Dlibunity='false'
build      : |
    %meson_build
install    : |
    %meson_install
