name       : switchboard
version    : 2.3.6
release    : 2
source     :
    - https://github.com/elementary/switchboard/archive/2.3.6.tar.gz : 1624f67ab200d490769fb994a0d3d3cb469e8c63cf0111448b36538f2a137691
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Pantheon extensible System Settings app designed
description: |
    Switchboard is just the container application for Switchboard Plugs, which provide the actual settings for various hardware and software.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - meson
    - vala
setup      : |
    %meson_configure -Dlibunity='false'
build      : |
    %meson_build
install    : |
    %meson_install
