name       : switchboard-plug-sound
version    : 2.2.1
release    : 2
source     :
    - https://github.com/elementary/switchboard-plug-sound/archive/2.2.1.tar.gz : 7c92c5eae0270832a3a740ab649cead6f80c85c7f123ca3733f84d192fb9537a
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Switchboard sound plug
description: |
    Sound plug for Switchboard which allows the user to set the audio and microphone volume and several sound-related settings.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - pkgconfig(switchboard-2.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
