name       : vscodium
version    : 1.35.1
release    : 2
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.35.1/codium_1.35.1-1560422401_amd64.deb : 35fbd8d6738a9736578c5ce3df2a964994df5a2ea9fd66d1c4b0fed6d6e01814
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
