name       : vscodium
version    : 1.34.0
release    : 1
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.34.0/vscodium_1.34.0-1558029460_amd64.deb : fb6cd50d94a4fac804d5bf87247c0de9ec191855551da18cb1a0904a6e9d08df
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
