name       : vscodium
version    : 1.36.0
release    : 3
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.36.0/codium_1.36.0-1562179425_amd64.deb : e9950d444a4d6b27039e67f4a162d6533443e036751044bbe26939e6da8d4916
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
