name       : vscodium
version    : 1.37.0
release    : 5
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.37.0/codium_1.37.0-1565550282_amd64.deb : f285ec317db26a09789cfd651f75644bdac209435ca0589c14abbfbb8d2b6f00
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - tar
    - binutils
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
