name       : awesomewm
version    : 4.3
release    : 2
source     :
        - https://github.com/awesomeWM/awesome/releases/download/v4.3/awesome-4.3.tar.xz : 78264d6f012350b371e339127aca485260bc0aa935eff578ba75ce1a00e11753
license    : GPL-2.0
summary    : Awesome window manager.
description: |
    Awesome window manager.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(lua)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xkbcommon)
    - imagemagick
    - lua-lgi
setup      : |
    if [ -d build ]; then rm -rf build; fi
    mkdir -p build
    cd build
    %cmake \
        -DCMAKE_BUILD_TYPE:STRING="Release" \
        -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
        -DXDG_CONFIG_DIR:PATH="/etc/xdg" \
        -DAWESOME_DATA_PATH:PATH="/usr/share/awesome" \
        -DAWESOME_DOC_PATH:PATH="/usr/share/doc/awesome" \
        -DAWESOME_MAN_PATH:PATH="/usr/share/man" \
        -DSYSCONFDIR:PATH="/etc" \
        -DAWESOME_XSESSION_PATH:PATH="/usr/share/xsessions" \
        -DCMAKE_INSTALL_RPATH:PATH="/usr/lib" \
        ../
build      : |
    %make
install    : |
    %make_install
