name       : cinnamon-session
version    : 4.2.1
release    : 1
source     :
    - https://github.com/linuxmint/cinnamon-session/archive/4.2.1.tar.gz : bff38239942dc990ccb57c35bde43c19ebc8708284410de53c100e12c7005663
license    : GPL-2.0
component  : desktop.cinnamon
summary    : Cinnamon session
description: |
    The Cinnamon session manager.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libcanberra)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(libsystemd)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xapp)
    - pkgconfig(xau)
    - pkgconfig(xcomposite)
    - pkgconfig(xext)
    - pkgconfig(xkbfile)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - gnome-common
    - xtrans
setup      : |
    %meson_configure -Dwith-docbook='false'
build      : |
    %meson_build
install    : |
    %meson_install
