name       : qterminal
version    : 0.14.1
release    : 1
source     :
    - https://github.com/lxqt/qterminal/archive/0.14.1.tar.gz : bf1ef3590f602b23f17538cda59cd68d60624375fa7a59f19d7cbb27d3d64c14
license    : GPL-2.0
component  : desktop.lxqt
summary    : A lightweight Qt-based terminal emulator
description: |
    QTerminal is a lightweight Qt terminal emulator based on QTermWidget.
    It is maintained by the LXQt project but can be used independently from this desktop environment.
    The only bonds are lxqt-build-tools representing a build dependency and the localization files which were outsourced to LXQt repository lxqt-l10n.
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(qtermwidget5)
    - lxqt-build-tools-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
