name       : gsignond
version    : 1.2.0
release    : 1
source     :
    - git|https://gitlab.com/accounts-sso/gsignond.git : 1.2.0
license    : GPLv3
summary    : SignOn Daemon (GLib).
description: |
    SignOn Daemon (GLib).
builddeps  :
    - gobject-introspection-devel
    - glib2-devel
    - glibc-devel
    - sqlite3-devel
    - meson
    - vala
setup      : |
    %meson_configure -Ddocumentation='false'
build      : |
    %meson_build
install    : |
    %meson_install
