name       : font-raleway-ttf
version    : 1
release    : 1
source     :
    - git|https://github.com/theleagueof/raleway.git : 15dd22b0a1699bbfbd4faab8efc1f92d95b8322a
license    : GPLv3
component  : desktop.pantheon
summary    : An elegant sans-serif, designed in a single thin weight.
description: |
    An elegant sans-serif, designed in a single thin weight.
install    : |
    mkdir -p $installdir/usr/share/fonts/Raleway
    install -Dm644 Raleway\ Thin.otf $installdir/usr/share/fonts/Raleway/RalewayThin.otf
    install -Dm644 Raleway\ Thin.ttf $installdir/usr/share/fonts/Raleway/RalewayThin.ttf
