name       : font-raleway-ttf
version    : 1
release    : 2
source     :
    - https://github.com/theleagueof/raleway/archive/15dd22b0a1699bbfbd4faab8efc1f92d95b8322a.tar.gz : ef9b8a05e9dc455a345ba5f5765a3c6993bb1e44ec92797a17fdd966e9504f2e
license    : OFL-1.1
component  : desktop.pantheon
summary    : An elegant sans-serif, designed in a single thin weight
description: |
    Raleway is an elegant sans-serif typeface, designed in a single thin weight.
    It is a display face that features both old style and lining numerals, standard and discretionary ligatures, a pretty complete set of diacritics, as well as a stylistic alternate inspired by more geometric sans-serif typefaces than its neo-grotesque inspired default character set.
install    : |
    mkdir -p $installdir/usr/share/fonts/Raleway
    install -Dm644 Raleway\ Thin.otf $installdir/usr/share/fonts/Raleway/RalewayThin.otf
    install -Dm644 Raleway\ Thin.ttf $installdir/usr/share/fonts/Raleway/RalewayThin.ttf
