name       : switchboard-plug-locale
version    : 2.4.1
release    : 1
source     :
    - git|https://github.com/elementary/switchboard-plug-locale.git : 2.4.1
license    : GPLv3
component  : desktop.pantheon
summary    : Switchboard Locale Plug.
description: |
    Switchboard Locale Plug.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - libgnome-desktop-docs
    - glib2-devel
    - glibc-devel
    - accountsservice-devel
    - ibus-devel
    - switchboard-devel
    - meson
    - vala
setup      : |
    patch -Np1 --ignore-whitespace -i ../../../../../work/files/vala-version.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
